// Constant.swift
// Copyright © SolovevAA. All rights reserved.

import Foundation

/// Названия цветов
enum NameColors {
    static let backgroundMainViewColor = "BackgroundMainViewColor"
    static let backgroundCategoryColor = "BackgroundCategoryColor"
    static let backgroundTextFieldColor = "BackgroundTextFieldColor"
    static let darkGrayTextColor = "DarkGrayTextColor"
    static let backgroundButtonColor = "BackgroundButtonColor"
    static let foregroundTextButtonColor = "ForegroundTextButtonColor"
    static let blackTextColor = "BlackTextColor"
    static let titleTextColor = "TitleTextColor"
    static let tabBarBackgroundColor = "TabBarBackgroundColor"
    static let lightGrayCircleColor = "LightGrayCircleColor"
    static let eyeColor = "EyeColor"
    static let whiteTextColor = "WhiteTextColor"
    static let storeNameTextColor = "StoreNameTextColor"
    static let saleBackgroundColor = "SaleBackgroundColor"
    static let recomendationStoreTextColor = "RecomendationStoreTextColor"
    static let profileNameTextColor = "ProfileNameTextColor"
    static let profileMenuTextColor = "ProfileMenuTextColor"
}

/// Названия изображений
enum NameImages {
    static let plusWhite = "PlusWhite"
    static let minusWhite = "MinusWhite"
    static let backLittle = "BackLittle"
    static let productHeartButton = "ProductHeartButton"
    static let productShareButton = "ProductShareButton"
    static let line = "Line"
    static let star = "Star"
    static let home = "Home"
    static let heart = "Heart"
    static let basket = "Basket"
    static let message = "Message"
    static let profile = "Profile"
    static let eyeSlash = "eye.slash"
    static let eye = "eye"
    static let horizontalLine = "HorizontalLine"
    static let search = "Search"
    static let profileImageMock = "ProfileImageMock"
    static let bottomChevron = "BottomChevron"
    static let darkHeart = "DarkHeart"
    static let plus = "Plus"
    static let upload = "Upload"
    static let chevron = "Chevron"
    static let back = "Back"
}

/// Названия шрифтов
enum NameFonts {
    static let montserratRegular = "Montserrat-Regular"
    static let montserratBold = "Montserrat-Bold"
}

/// Константы
enum Constants {
    static let persistentContainerName = "CoreDataUserModel"
    static let storeQueryText = "https://run.mocky.io/v3/"
    static let heartViewText = "Heart View"
    static let basketViewText = "Basket View"
    static let messageViewText = "Message View"
    static let addToCardViewText = "AddToCard View"
    static let quantityText = "Quantity:"
    static let dollarText = "$"
    static let sharpText = "#"
    static let addToCardText = "ADD TO CARD"
    static let reviewsText = "reviews"
    static let colorText = "Color:"
    static let okText = "Ok"
    static let userNotExistText = "User not exist"
    static let loginText = "Login"
    static let passwordText = "Password"
    static let firstNameText = "First name"
    static let welcomeBackText = "Welcome back"
    static let userAlreadyExistText = "User already exist"
    static let signInText = "Sign in"
    static let emailIncorrectText = "Email incorrect"
    static let emailText = "Email"
    static let lastNameText = "Last name"
    static let logInText = "Log in"
    static let haveAccountText = "Already have an account?"
    static let GoogleText = "Google"
    static let signInWithGoogleText = "Sign in with Google"
    static let appleText = "Apple"
    static let signInWithAppleText = "Sign in with Apple"
    static let emailFormatText = "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}"
    static let emailPredicateText = "SELF MATCHES %@"
    static let latestDealsText = "Latest deals"
    static let flashSaleText = "Flash sale"
    static let brandsText = "Brands"
    static let tradeBuyText = "Trade buy"
    static let bataText = "bata"
    static let lookingText = "What are you looking for ?"
    static let locationText = "Location"
    static let offText = "% off"
    static let viewAllText = "View all"
    static let changePhotoText = "Change photo"
    static let uploadItemText = "Upload item"
    static let satriaAdhiPradanaText = "Satria Adhi Pradana"
    static let profileText = "Profile"
}
